# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test_min_node_version:
    docker:
      - image: circleci/node:6
      # https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests against our npm build (on minimum node version)
      - run: yarn build && yarn test-dist

  coverage_test_publish:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run coveralls first in case tests fail (and against 'src')
      - run: yarn coveralls

      # run tests against our npm build (on this node version too)
      - run: yarn build && yarn test-dist

      # Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
      - run: openssl aes-256-cbc -d -in gadicc_github_circleci_scripts.enc -out /tmp/git_deploy_key -k "$REPO_ENC_KEY"
      # Make sure only the current user can read the private key
      - run: chmod 600 /tmp/git_deploy_key
      # Create a script to return the passphrase environment variable to ssh-add
      - run: echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
      # Start the authentication agent
      - run: eval "$(ssh-agent -s)"
      # Add the key to the authentication agent
      - run: DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null

      # if test passed, try release, but end true for no release needed
      - run: npm run semantic-release

workflows:
  version: 2
  default:
    jobs:
      - test_min_node_version
      - coverage_test_publish
